08:57:38.613 [main] DEBUG org.hibernate.SQL - select customer0_.idCustomer as idCustom1_0_0_, customer0_.address as address2_0_0_, customer0_.idUser as idUser3_0_0_, customer0_.name as name4_0_0_, customer0_.telephone as telephon5_0_0_ from Customers customer0_ where customer0_.idCustomer=?
08:57:38.633 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [1]
08:57:38.650 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([address2_0_0_] : [VARCHAR]) - [First Street]
08:57:38.650 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idUser3_0_0_] : [INTEGER]) - [2]
08:57:38.650 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([name4_0_0_] : [VARCHAR]) - [Firstmundo]
08:57:38.652 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([telephon5_0_0_] : [VARCHAR]) - [11111111]
08:57:38.673 [main] DEBUG org.hibernate.SQL - delete from Customers where idCustomer=?
08:57:38.673 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [29]
08:57:38.678 [main] ERROR org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1]
08:57:38.767 [main] DEBUG org.hibernate.SQL - delete from Customers where idCustomer=?
08:57:38.768 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [1]
08:57:38.802 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Cannot delete or update a parent row: a foreign key constraint fails (`webstorelaura`.`purchases`, CONSTRAINT `FK_idCustomer` FOREIGN KEY (`idCustomer`) REFERENCES `customers` (`idcustomer`) ON DELETE RESTRICT ON UPDATE RESTRICT)
08:57:38.878 [main] DEBUG org.hibernate.SQL - select i.* from Items i inner join Purchases p on p.idItem = i.idItem where p.idCustomer = ? group by i.idItem
08:57:38.878 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [1]
08:57:38.884 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem] : [INTEGER]) - [1]
08:57:38.885 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([company] : [VARCHAR]) - [HP]
08:57:38.885 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([name] : [VARCHAR]) - [Computer]
08:57:38.886 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([price] : [DOUBLE]) - [540.0]
08:57:38.886 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem] : [INTEGER]) - [5]
08:57:38.886 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([company] : [VARCHAR]) - [Xiaomi]
08:57:38.886 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([name] : [VARCHAR]) - [Smartphone]
08:57:38.886 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([price] : [DOUBLE]) - [180.0]
08:57:38.935 [main] DEBUG org.hibernate.SQL - select purchase0_.idPurchase as idPurcha1_2_, purchase0_.idCustomer as idCustom3_2_, purchase0_.date as date2_2_, purchase0_.idItem as idItem4_2_ from Purchases purchase0_ where purchase0_.date=?
08:57:38.936 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [DATE] - [2018-11-11]
08:57:38.944 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha1_2_] : [INTEGER]) - [3]
08:57:38.944 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idCustom3_2_] : [INTEGER]) - [3]
08:57:38.946 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([date2_2_] : [DATE]) - [2018-11-11]
08:57:38.946 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem4_2_] : [INTEGER]) - [4]
08:57:38.946 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha1_2_] : [INTEGER]) - [5]
08:57:38.947 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idCustom3_2_] : [INTEGER]) - [3]
08:57:38.947 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([date2_2_] : [DATE]) - [2018-11-11]
08:57:38.947 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem4_2_] : [INTEGER]) - [6]
08:57:38.953 [main] DEBUG org.hibernate.SQL - select purchase0_.idPurchase as idPurcha1_2_, purchase0_.idCustomer as idCustom3_2_, purchase0_.date as date2_2_, purchase0_.idItem as idItem4_2_ from Purchases purchase0_ where purchase0_.date=?
08:57:38.953 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [DATE] - [2018-11-11]
08:57:38.959 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha1_2_] : [INTEGER]) - [3]
08:57:38.959 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha1_2_] : [INTEGER]) - [5]
08:57:38.960 [main] DEBUG org.hibernate.SQL - select purchase0_.idPurchase as idPurcha1_2_0_, purchase0_.idCustomer as idCustom3_2_0_, purchase0_.date as date2_2_0_, purchase0_.idItem as idItem4_2_0_ from Purchases purchase0_ where purchase0_.idPurchase=?
08:57:38.961 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [1]
08:57:38.966 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idCustom3_2_0_] : [INTEGER]) - [1]
08:57:38.966 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([date2_2_0_] : [DATE]) - [2018-11-07]
08:57:38.967 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem4_2_0_] : [INTEGER]) - [1]
08:57:38.967 [main] DEBUG org.hibernate.SQL - select item0_.idItem as idItem1_1_0_, item0_.company as company2_1_0_, item0_.name as name3_1_0_, item0_.price as price4_1_0_ from Items item0_ where item0_.idItem=?
08:57:38.967 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [1]
08:57:38.973 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([company2_1_0_] : [VARCHAR]) - [HP]
08:57:38.973 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([name3_1_0_] : [VARCHAR]) - [Computer]
08:57:38.973 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([price4_1_0_] : [DOUBLE]) - [540.0]
08:57:38.975 [main] DEBUG org.hibernate.SQL - select review0_.idReview as idReview1_3_, review0_.date as date2_3_, review0_.description as descript3_3_, review0_.idPurchase as idPurcha4_3_, review0_.rating as rating5_3_, review0_.title as title6_3_ from Reviews review0_
08:57:38.980 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idReview1_3_] : [INTEGER]) - [5]
08:57:38.980 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([date2_3_] : [VARCHAR]) - [2018-11-11]
08:57:38.980 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([descript3_3_] : [VARCHAR]) - [This review blocks the deletion of the text purchase.]
08:57:38.981 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha4_3_] : [INTEGER]) - [5]
08:57:38.981 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idPurcha4_3_] : [INTEGER]) - [5]
08:57:38.981 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([rating5_3_] : [INTEGER]) - [1]
08:57:38.981 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([title6_3_] : [VARCHAR]) - [Test review 2]
08:57:38.981 [main] DEBUG org.hibernate.SQL - select purchase0_.idPurchase as idPurcha1_2_0_, purchase0_.idCustomer as idCustom3_2_0_, purchase0_.date as date2_2_0_, purchase0_.idItem as idItem4_2_0_ from Purchases purchase0_ where purchase0_.idPurchase=?
08:57:38.981 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [5]
08:57:38.987 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idCustom3_2_0_] : [INTEGER]) - [3]
08:57:38.987 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([date2_2_0_] : [DATE]) - [2018-11-11]
08:57:38.987 [main] TRACE org.hibernate.type.descriptor.sql.BasicExtractor - extracted value ([idItem4_2_0_] : [INTEGER]) - [6]
08:57:38.997 [main] DEBUG org.hibernate.SQL - delete from Reviews where idPurchase in (select purchase1_.idPurchase from Purchases purchase1_ where purchase1_.idCustomer=?)
08:57:38.997 [main] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [INTEGER] - [20]
08:59:14.859 [main] INFO  quevedo.hibernatetest.Main - probando HIBERNTE
08:59:18.614 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:356) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:199) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:444) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:515) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) [HikariCP-2.6.1.jar:?]
	at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59) [hibernate-hikaricp-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:100) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:175) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:119) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:84) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:474) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at quevedo.hibernatetest.HibernateUtil.<clinit>(HibernateUtil.java:38) [classes/:?]
	at quevedo.hibernatetest.Main.addEntityAlone(Main.java:106) [classes/:?]
	at quevedo.hibernatetest.Main.main(Main.java:29) [classes/:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_144]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_144]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
09:14:18.438 [main] INFO  quevedo.hibernatetest.Main - probando HIBERNTE
09:14:22.185 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:356) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:199) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:444) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:515) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) [HikariCP-2.6.1.jar:?]
	at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59) [hibernate-hikaricp-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:100) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:175) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:119) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:84) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:474) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at quevedo.hibernatetest.HibernateUtil.<clinit>(HibernateUtil.java:38) [classes/:?]
	at quevedo.hibernatetest.Main.addEntityAlone(Main.java:106) [classes/:?]
	at quevedo.hibernatetest.Main.main(Main.java:29) [classes/:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_144]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_144]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
09:20:04.368 [main] INFO  quevedo.hibernatetest.Main - probando HIBERNTE
09:20:08.137 [main] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:356) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:199) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:444) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:515) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:112) [HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72) [HikariCP-2.6.1.jar:?]
	at org.hibernate.hikaricp.internal.HikariCPConnectionProvider.configure(HikariCPConnectionProvider.java:59) [hibernate-hikaricp-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:100) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:175) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:119) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:84) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:474) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:689) [hibernate-core-5.4.0.Final.jar:5.4.0.Final]
	at quevedo.hibernatetest.HibernateUtil.<clinit>(HibernateUtil.java:38) [classes/:?]
	at quevedo.hibernatetest.Main.addEntityAlone(Main.java:106) [classes/:?]
	at quevedo.hibernatetest.Main.main(Main.java:29) [classes/:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_144]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_144]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_144]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:152) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-java-8.0.13.jar:8.0.13]
	... 35 more
